name: Deploy Backend to Server

on:
  push:
    paths:
      - 'graduationProject/**'
      - '.github/workflows/backend-deploy.yml'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Логинимся в Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. SSH на сервер, обновляем репозиторий, строим новый Docker образ
      - name: SSH to Server, Git Pull and Build Docker Image
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Переходим в каталог с бэкендом
            cd ~/vintageBot/graduationProject

            # Обновляем репозиторий
            git pull origin main

            # Строим Docker образ
            docker build -t ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest .

            # Пушим новый образ в Docker Hub
            docker push ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest

      # 4. SSH на сервер и перезапуск контейнера
      - name: SSH to Server and Redeploy Backend
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Входим в каталог с Docker Compose
            cd ~/vintageBot/compuseDiplom

            # Тянем последний образ бэкенда
            docker-compose pull backend

            # Перезапускаем контейнер
            docker-compose up -d backend
