name: Deploy Backend to Server

on:
  push:
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show last commit message
        run: |
          echo "::notice::Last commit:"
          git log -1 --pretty=oneline

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image (no cache)
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest .

      - name: Inspect built image digest
        run: |
          echo "::notice::Built image digest:"
          docker inspect ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest --format='{{index .RepoDigests 0}}'

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest

      - name: SSH to Server and Redeploy Backend
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧼 Stop and remove old backend"
            cd ~/vintageBot/compuseDiplom
            docker-compose down backend || true

            echo "🧹 Remove old images"
            docker image rm -f $(docker images --filter=reference="${{ secrets.DOCKER_USERNAME }}/diploma_backend*" -q) || true

            echo "📥 Pull new image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest

            echo "🚀 Start backend"
            docker-compose up -d --force-recreate backend
