name: Deploy Backend (Only Backend)

on:
  push:
    paths:
      - 'graduationProject/**'
      - '.github/workflows/backend-deploy.yml'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Устанавливаем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Кеш Docker
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Сборка Docker-образа
      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest ./graduationProject

      # 5. Docker login
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Push образа
      - name: Push Backend Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest

      # 7. SSH на сервер и перезапуск backend
      - name: SSH into Server and Restart Backend
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest

            docker stop diploma_backend || true
            docker rm diploma_backend || true

            docker run -d \
              --name diploma_backend \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e DATA_URL=${{ secrets.DATA_URL }} \
              -e JAVA_OPTS=${{ secrets.JAVA_OPTS }} \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e ACCESS_KEY=${{ secrets.ACCESS_KEY }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e REG=${{ secrets.REG }} \
              -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} \
              -v /root/diploma_logs:/opt/app/logs \
              --network diploma_default \
              ${{ secrets.DOCKER_USERNAME }}/diploma_backend:latest
